### PR TITLE
Update GroupFinder_Readme.md

### PR DESCRIPTION
**Pull request by SarahCKopf**
**Thank you for your code contribution, we will take your code suggestion into consideration. It will be reviewed, and based on code quality and need addressed, we will determine acceptance. If this code addresses a feature request or issue, be sure to link to that issue.** 

### Description 

KFS Advanced Group Finder ReadMe.md

##### What does the change add or fix?

Created/Updated KFS Advanced Group Finder ReadMe.md from Rock shop documentation

---------

##### Who reported, requested, or paid for the change?

Fellowship Greenville

---------

##### Does this update or add options to the block UI?

No

---------

##### What files does it affect?

GroupFinder/ReadMe.md

---------

##### Is it a breaking change for other versions/clients?

No

### CODE REVIEW

**Comment by nateh777** [comment]
@SarahCKopf @KelleyLangkamp just a question, do you think we should include a screenshots of what the "collapsible" filters do? I had them in my temporary readme (https://github.com/KingdomFirst/RockBlocks/blob/master/Groups/GroupFinder_Readme.md), I am fine removing them if you think it is not helpful, just wondering if we should include any front end screenshots in the documentation or not.

**Comment by KelleyLangkamp** [comment]
@SarahCKopf Yes, when you get back, let's add the collapsible filters screenshots to the readme. We'll need to update the pdf for the Rock Shop too.

**Comment by nateh777** [comment]
And just to clarify, the blue ones, not the orange ones, those were client specific styles. Let me know if you need different screenshots at all.

**Review by SarahCKopf — COMMENTED** [review]
I have added the filters screenshots.

**Review by nateh777 — APPROVED** [review]

**Pull request merged**
